### ISSUE TITLE
Support for sudo in CB 3.8

### ISSUE THREAD

**Issue by dontascii** [chrisschmitz/commandbox-hostupdater#10]
Hi Chris, 
Any plans to update your module now that CB supports sudo commands?  No longer need to start commandbox as root.  You could simply issue 'sudo !!' if the hosts file update fails and it will prompt user for super user creds.  

I use sudo for interface alias commands as well as host file mods in a similar CB module.  I like the way you do it in an interceptor though,  so I've been watching your project closely. 

Thanks! 
Joel

**Comment by chrisschmitz** [comment]
Hey Joel.

as a matter of fact I already have a version of the module that utilizes the CB "run" command to use sudo for editing the hosts file. I need to do some cleaning up for this feature, finalize the hostAliases feature that was requested and then adjust the readme.  

You can expect the new version to go live within the next two weeks.

Cheers

Chris
