### ISSUE TITLE
Dynamic Host values need to be processed before HostUpdater writes to host file

### ISSUE THREAD

**Issue by gpickin** [chrisschmitz/commandbox-hostupdater#14]
A lot of customers use something like this for hosts - ${host:127.0.0.1} 
host updater tries to add that to the hosts file, not the resolved value.

According to Brad

Sounds like the host updater needs to use a slightly different method to get the values
It's probably manually reading the file and not resolving the placeholders.

Looks like it's getting that from the interception announcement
https://github.com/chrisschmitz/commandbox-hostupdater/blob/master/ModuleConfig.cfc#L9
ModuleConfig.cfc:9

arguments.interceptData.serverDetails.serverJSON.web.host ?:            // host provided in server.json?

Ooh, the server json _hasn't_ had system settings replaced at that point yet!

preServerStart is called before the CLI args are written back out to the server.json file, but the system settings aren't resolved until after that.

Chris has to use preServerStart though, that's the only interception point that's early enough that CommandBox hasn't already tried to use the host (which happens as part of the port logic when choosing a random port and detecting if the port is in use)

Chris could probably work around it by duplicating the serverJSON struct and running it through this:
systemSettings.expandDeepSystemSettings( serverJSON );

**Comment by chrisschmitz** [comment]
Version 1.7.0 adds support for system variables
