### ISSUE TITLE
Adding more IP mappings

### ISSUE THREAD

**Issue by cybersonic** [chrisschmitz/commandbox-hostupdater#8]
Sometimes I would like to add more than just the main domain for the site. I would need to add database mappings (for example `127.0.0.0    db` so it would be good if the plugin could update a number of host mappings rather than just the site one.

**Comment by chrisschmitz** [comment]
Seems very similar to issue #9 , I will look into this over the next days

**Comment by iknowkungfoo** [comment]
Issue #9 has been merged. Check if this addresses your issue.

**Comment by chrisschmitz** [comment]
You can now define host aliases
