### ISSUE TITLE
Allow host aliases

### ISSUE THREAD

**Issue by iknowkungfoo** [chrisschmitz/commandbox-hostupdater#9]
Working on a project where the site has multiple sub-domains. Would like to support an array of aliases on the same IP address. 

```
 "web":{
 	"host":"myDomain.localhost",
 	"hostAlias": [
 		"sub1.myDomain.localhost", 
 		"sub2.myDomain.localhost", 
 		"sub3.myDomain.localhost",
 	]
}
```

**Comment by chrisschmitz** [comment]
Sorry, for the delay in responding, I was pretty occupied lately. 
I think that should be possible, I will look into this over the next days.
Thanks for the suggestion!

**Comment by iknowkungfoo** [comment]
Implemented w/ https://github.com/chrisschmitz/commandbox-hostupdater/pull/12,
